version: '3'

services:
  nakama:
    container_name: nakama
    image: heroiclabs/nakama:3.22.0
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address ${DATABASE_URL} &&
        exec /nakama/nakama --name nakama1 --database.address ${DATABASE_URL} --logger.level DEBUG --session.token_expiry_sec 7200 --metrics.prometheus_port 9100
    restart: unless-stopped
    volumes:
      - ./server-data/modules:/nakama/data/modules
      - ./server-data/logs:/nakama/data/logs
    ports:
      - "7350:7350"
      - "7351:7351"
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_7MzOT0uqbJYt@ep-little-dream-an51a9t5.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require